##############################################################
# LNAMP 开发环境
# 应用：Nginx、PHP with FPM、MySQL
# 说明：通过修改 VERSION 及 image 后面的版本号以切换到不同版本启动
##############################################################

version: '3'

# 配置服务
services:

  # Nginx
  # 版本：1.12、1.14（默认）、1.16
  # https://hub.docker.com/_/nginx
  nginx:
    build:
      context: ./build/nginx
      args:
        VERSION: 1.14
    image: lnmp/nginx:1.14
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5g"
    depends_on:
      - php_fpm
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./www:/usr/share/nginx/html:cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/vhosts:/etc/nginx/conf.d:rw
      - ./conf/nginx/rewrite:/etc/nginx/rewrite:ro
      - ./conf/php_fpm/sock:/sock
      - ./log/nginx:/var/log/nginx:rw
    links:
      - php_fpm
    networks:
      - lnmp-net-bakend

  # PHP with fpm
  # 版本：5.6、7.0（默认）、7.1、7.2、7.3
  # https://hub.docker.com/_/php
  php_fpm:
    build:
      context: ./build/php70_fpm
      args:
        - VERSION=7.0
    image: lnmp/php_fpm:7.0
    restart: always
    depends_on:
      - mysql
    expose:
        - "9001"
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./www:/var/www/html:cached
      - ./conf/php_fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php_fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./conf/php_fpm/sock:/sock
      - ./log/php_fpm:/usr/local/log:rw
    links:
      - "mysql:docker-server-mysql"
    networks:
      - lnmp-net-bakend

  # MySQL
  # 版本：5.6、5.7（默认）、8.0
  # https://hub.docker.com/_/mysql
  mysql:
    build:
      context: ./build/mysql
      args:
        - VERSION=5.7
    image: lnmp/mysql:5.7
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./log/mysql/:/var/log/mysql/:rw
    networks:
      - lnmp-net-bakend

# 配置网络
networks:
  lnmp-net-bakend:
    driver: bridge
